src.main=src/main
src.java=${src.main}/java
src.web=${src.main}/webapp
src.test=src/test/java
resources=${src.main}/resources
lib=lib

build=build
build.classes=${build}/classes
build.ar=${build}/${ant.project.name}
build.web.inf=${build.ar}/WEB-INF
build.lib=${build.web.inf}/lib
build.web.xml=${build.web.inf}/web.xml

build.test=${build}/test
test.classes=${build.test}/test-classes
test.report=${build.test}/test-report

junit=${lib}/junit-4.13.2.jar
hamcrest=${lib}/hamcrest-core-1.3.jar