src.main=src/main
src.java=${src.main}/java
src.web=${src.main}/webapp
resources=${src.main}/resources
lib=lib

build=build
build.classes=${build}/classes
build.ar=${build}/${ant.project.name}
build.web.inf=${build.ar}/WEB-INF
build.lib=${build.web.inf}/lib
build.web.xml=${build.web.inf}/web.xml