src.main=src/main
src.java=${src.main}/java
src.web=${src.main}/webapp
src.test=src/test/java
resources=${src.main}/resources
lib=lib

build=build
build.classes=${build}/classes
build.ar=${build}/${ant.project.name}
build.web.inf=${build.ar}/WEB-INF
build.lib=${build.web.inf}/lib
build.web.xml=${build.web.inf}/web.xml
build.war=${build}/${ant.project.name}.war

build.test=${build}/test
test.classes=${build.test}/test-classes
test.report=${build.test}/test-report

build.doc=${build}/doc

junit=${lib}/junit-4.13.2.jar
hamcrest=${lib}/hamcrest-core-1.3.jar

xerces=${lib}/xercesImpl-2.12.2.jar
xerces.parser=org.apache.xerces.parsers.SAXParser

contrib=${lib}/ant-contrib-1.0b3.jar

comp.args=
comp.ver=17
vm.args=-XX:MaxHeapSize=1G -XX:MaxMetaspaceSize=256m
build.env=${build}/env
build.env.classes=${build.env}/classes
build.env.ar=${build.env}/${ant.project.name}
build.env.web.inf=${build.env.ar}/WEB-INF
build.env.lib=${build.env.web.inf}/lib
build.env.web.xml=${build.env.web.inf}/web.xml
build.env.war=${build.env}/${ant.project.name}.war
